spring:
  application:
    name: ${APP_NAME:weshopify-brands-service}

  data:
    mongodb:
      database: WESHOPIFY-BRANDS-SERVICE
      uri: ${MONGO_DB_URI:mongodb+srv://mongo:mongo@cluster0.eczp2kn.mongodb.net/?retryWrites=true&w=majority}
      auto-index-creation: ${MONGO_AUTO_INDEX_CREATION:true}
    redis:
      host: '${REDIS_SERVER_HOST:cache.weshopifyapp.in}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'
      
  cloud:
    loadbalancer:
      enabled: true 
      stats:
        micrometer:
          enabled: true
    openfeign:
      micrometer:
        enabled: true
        
      
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    prefer-ip-address: true
    
server:
  port: ${APP_PORT:5017}
  
services: 
  categories: 
     #base-uri: '${CATEGORIES_BASE_URI:http://localhost:5016/categories}'
     base-uri: http://${CATEGORIES_SVC_HOST:localhost}:${CATEGORIES_SVC_PORT:5016}
     #access-token: eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ3ZXNob3BpZnktYWRtaW4iLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwiaXNzIjoiaHR0cHM6XC9cL2lhbS53ZXNob3BpZnlhcHAuaW5cL29hdXRoMlwvdG9rZW4iLCJnaXZlbl9uYW1lIjoiV2VzaG9waWZ5LUFkbWluaXN0cmF0b3IiLCJhdWQiOiJRTEdHY25tM1gzYVc2MU4wdUZFYzh1S3FfRkFhIiwiV2VzaG9waWZ5VXNlcklkIjoiYTZjY2U5ZTgtZDEzOC00NDk2LWFkNjMtODE1YWJkMDg1Y2Q1IiwibmJmIjoxNjc1NDkyNjI2LCJhenAiOiJRTEdHY25tM1gzYVc2MU4wdUZFYzh1S3FfRkFhIiwic2NvcGUiOiJvcGVuaWQiLCJ3ZXNob3BpZnlVc2VyU3RhdHVzIjoiZmFsc2UiLCJleHAiOjE2NzU0OTYyMjYsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzU0OTI2MjYsImZhbWlseV9uYW1lIjoiV2VzaG9waWZ5IiwianRpIjoiNTg4N2ZmZTgtZDAzNS00ODRiLTg1NmUtYzZkODMxZDFlNjUxIiwiZW1haWwiOiJ3ZXNob3BpZnktYWRtaW5AeW9wbWFpbC5jb20ifQ.JtrjNooQ0fNfBKmPnP1KlBdEcJTGaYcBjQ9_jSr__cm0NlZkTK4dAiJRHk9GkPsi-xGzfyIW1ge7fv4fO7DFSYxUO94cv1OVSmN2M8GRxv6GsjUksVc7sMiZaXw87pRbFxmErrcRvaliWgeTPlSkukaVbrwPWP63zw8JW44MAGGJFznmnXnE33eHne57GIm1aU2UmfT7xlf9yoq8g8gweYWN7dbbQDLiETtRPaxKAmBdnlsS9pkjBqbJd1aZO6NBQSMvywcB5U-iKsrtAlZoRAsNnxugkavLaX3AUUCoSEER-QXEyz024eG3n-tr4UKtFyMhushzp73HCpH_2XnxRA
management:
  zipkin:
    tracing:
      endpoint: http://{ZIPKIN_HOST:localhost}:{ZIPKIN_PORT:9411}
      